"""AI service boundary for AI Work Coach."""
from .schemas import AnalysisResponse, AIOpportunity, OpportunityLevel, SkillToPractice, WorkflowStep

SYSTEM_INSTRUCTION = """You are a workplace AI coach. Your job is not simply to perform the employee's task. Help the employee understand how AI can assist with the task while keeping appropriate human judgement. Return a practical AI-assisted workflow, a ready-to-use prompt, the skill being practised, expected benefit, and what requires human verification. Use HIGH, MEDIUM, or LOW AI opportunity where appropriate. Be cautious with confidential information, personal data, legal decisions, employment decisions, financial approvals, medical information, security credentials, and other consequential decisions. Never advise the employee to delegate final judgement in those areas to AI."""

async def analyze_task_with_ai(task: str) -> AnalysisResponse:
    """Return a structured plan. Replace this fallback with a real LLM call before final submission."""
    # Development fallback. Replace with real LLM call before final submission.
    return AnalysisResponse(task=task, ai_opportunity=AIOpportunity(level=OpportunityLevel.HIGH, message="AI can accelerate the analysis and first draft, while you should validate the numbers and make the final business judgement."), recommended_workflow=[WorkflowStep(step=1, title="Prepare the context", description="Collect the relevant source material, reporting period, and the audience for the work."), WorkflowStep(step=2, title="Work with AI", description="Ask AI to identify patterns, changes, and an initial structure for the task."), WorkflowStep(step=3, title="Verify", description="Check important facts, numbers, and claims against the original source material."), WorkflowStep(step=4, title="Finish with human judgement", description="Choose what matters for the audience and finalise the work using your professional context.")], skill_to_practice=SkillToPractice(name="Prompt Structuring", category="Core AI Skills", level="Building"), ready_to_use_prompt=("Help me analyse this workplace task: " + task + "\n\nFirst, identify the key information, patterns, and questions I should consider. Then create a clear first draft for my manager. Flag assumptions and any details I must verify against the original source before sharing."), expected_benefit="Potentially reduces repetitive analysis and first-draft work while keeping the important review and business judgement with you.", human_review="Verify source facts, figures, and conclusions before sharing the final result. Use your business context to decide which insights matter.")
